### ISSUE TITLE
GRUB Installation Failed

### ISSUE THREAD

**Issue by vgrant** [awesomebytes/alienware15r3_ubuntu14#1]
I tried running through this and I ran into and issue with GRUB after setting the partitions and hitting 'Install now':

grub-efi-amd64-signed failed to install into /target/. Without GRUB boot loader,
the installed system will not boot

Trying to sort it out but if you have any insight that would be helpful. I forked the repo and will update it with what I find/solve with a pull request incase it will be useful to others.

**Comment by awesomebytes** [comment]
My first guess would be to try to use boot-repair to fix it. On a quick google that I'm sure you already did that's the first answer for example [here](http://askubuntu.com/questions/789998/16-04-new-installation-gives-grub-efi-amd64-signed-failed-installation-target).

Are you sure you chose the correct partition on where to install the boot loader? As I say in my instructions:

    **IMPORTANT** now you need to change the Device for boot loader installation to /dev/nvme0n1.

Maybe you have some BIOS option that is not letting you write on the boot sector/partition? Are you booting from UEFI? Like I said [here](https://github.com/awesomebytes/alienware15r3_ubuntu14#disable-secure-boot).

Let me know if you get to fix it or you can give some extra feedback and maybe we can figure it out.

**Comment by awesomebytes** [comment]
Hey @vgrant  did you manage to fix this problem?

**Comment by vgrant** [comment]
Sorry, got caught up with a project that delivered a few hours ago actually. I had some initial luck with what was suggested before but nothing solid. I wasn't able to give it an honest and comprehensive try yet so I was leaving it open as a badge of shame for motivation.

I will report back with more in the coming week.

**Comment by awesomebytes** [comment]
Sure, I updated a bit the guide about nvidia and CUDA stuff as it has been updated upstream. Good news, everything works and faster :)

**Comment by vgrant** [comment]
I started from scratch with the updated guide and everything worked perfectly! Thanks so much for all the effort you put into this. I did update and break the install again but I've done that many times before so it should be all good. I tend to use this laptop in a 'wipe at anytime state' so if you need a beta tester for guide updates I'd be happy to contribute.
